"""Clinical report models — output contract for the Synthesis Agent."""

from pydantic import BaseModel, Field


class CitedRecommendation(BaseModel):
    """A single clinical recommendation with its evidence citation.

    The Synthesis Agent MUST ground every recommendation in a retrieved
    guideline chunk. Recommendations without citations are rejected.
    """

    recommendation: str = Field(
        description="The clinical recommendation text",
    )
    citation_chunk_ids: list[str] = Field(
        description="List of GuidelineMatch chunk_ids that support this recommendation",
    )
    confidence: str = Field(
        default="moderate",
        description="Confidence level: 'high', 'moderate', or 'low' based on evidence strength",
    )


class ClinicalReport(BaseModel):
    """The final clinical decision support report.

    This is the end product of the entire MediAgent pipeline.
    Every claim must be grounded in upstream data — DDI database
    results and retrieved guideline chunks. No hallucinated advice.
    """

    patient_summary: str = Field(
        description="Brief structured summary of the patient case (2-3 sentences)",
    )
    risk_level: str = Field(
        description="Overall risk assessment: 'low', 'moderate', 'high', or 'critical'",
    )
    interaction_warnings: list[str] = Field(
        default_factory=list,
        description="Human-readable warnings about detected drug interactions",
    )
    recommendations: list[CitedRecommendation] = Field(
        default_factory=list,
        description="Clinical recommendations, each with evidence citations",
    )
    flags_for_clinician: list[str] = Field(
        default_factory=list,
        description="Items requiring urgent clinician attention or HITL review",
    )
    disclaimer: str = Field(
        default=(
            "This report is generated by an AI clinical decision support system. "
            "It is intended to assist, not replace, clinical judgment. "
            "All recommendations must be reviewed by a qualified healthcare professional."
        ),
        description="Medical-legal disclaimer — always present in output",
    )
